# Generated by Django 3.2.8 on 2023-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/web.jpeg', null=True, upload_to=''),
        ),
    ]
