export const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpod.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Iphone 11 pro",
    image: "/images/phone.jpg",
    description:
      "Iphone 11 pro technology lets you connect it with compatible devices wirelessly High-quality",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 0,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Camera Cannon EOS",
    image: "/images/camera.jpg",
    description:
      "Camera Cannon EOS technology lets you connect it with compatible devices wirelessly High-quality",
    brand: "Cannon",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Sony Playstation 4 Camera Cannon EOS",
    image: "/images/playstation.jpg",
    description:
      "Sony Playstation 4 technology lets you connect it with compatible devices wirelessly High-quality",
    brand: "Sony",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Logitech G-Series  Camera Cannon EOS",
    image: "/images/mouse.jpg",
    description:
      "Logitech G-Series technology lets you connect it with compatible devices wirelessly High-quality",
    brand: "Sony",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Amazon Logitech G-Series ",
    image: "/images/alexa.jpg",
    description:
      "Amazon technology lets you connect it with compatible devices wirelessly High-quality",
    brand: "Amazon",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
];
